"""GENERATED manifest of the winning hoid kernels for the UNet and the VAE
decoder — do not edit."""

KERNELS = {
    'dual_geglu': {
        'format': 'cutedsl',
        'entry': 'dual_geglu_entry',
        'file': 'dual_geglu.cutedsl.py',
        'sha256': 'fa8c7ea0066cce798e1ef76ad42c4ade84a84b576d3edfb1987ccfcb9da1dd8b',
        'options': '--opt-level=2',
        'compile_variants': [
            {
                'CLUSTER_M': 2,
                'CLUSTER_N': 1,
                'K': 640,
                'M': 8192,
                'MAX_CLUSTERS': 74,
                'O': 2560,
                'TILE_M': 256,
                'TILE_N': 128,
                'TWO_CTA': True,
            },
            {
                'CLUSTER_M': 2,
                'CLUSTER_N': 1,
                'K': 1280,
                'M': 2048,
                'MAX_CLUSTERS': 74,
                'O': 5120,
                'TILE_M': 256,
                'TILE_N': 128,
                'TWO_CTA': True,
            },
        ],
        'shape_variants': [
            [
                [
                    2048,
                    5120,
                    1,
                ],
                [
                    2048,
                    1280,
                    1,
                ],
                [
                    10240,
                    1280,
                    1,
                ],
                [
                    10240,
                ],
            ],
            [
                [
                    8192,
                    2560,
                    1,
                ],
                [
                    8192,
                    640,
                    1,
                ],
                [
                    5120,
                    640,
                    1,
                ],
                [
                    5120,
                ],
            ],
        ],
    },
    'fmha': {
        'format': 'cutedsl',
        'entry': 'fmha_entry',
        'file': 'fmha.cutedsl.py',
        'sha256': 'ecfaa096a010115d2f0f40d5f2c7fa64a9fcb2524e2d0a78c7199876478de8b1',
        'options': '--opt-level=2',
        'compile_variants': [
            {
                'B': 2,
                'D': 64,
                'H': 10,
                'SKV': 77,
                'SQ': 4096,
            },
            {
                'B': 2,
                'D': 64,
                'H': 10,
                'SKV': 4096,
                'SQ': 4096,
            },
            {
                'B': 2,
                'D': 64,
                'H': 20,
                'SKV': 1024,
                'SQ': 1024,
            },
        ],
        'shape_variants': [
            [
                [
                    2,
                    1024,
                    20,
                    1,
                    64,
                ],
                [
                    2,
                    1024,
                    20,
                    1,
                    64,
                ],
                [
                    2,
                    1024,
                    20,
                    1,
                    64,
                ],
                [
                    2,
                    1024,
                    20,
                    1,
                    64,
                ],
            ],
            [
                [
                    2,
                    4096,
                    10,
                    1,
                    64,
                ],
                [
                    2,
                    4096,
                    10,
                    1,
                    64,
                ],
                [
                    2,
                    77,
                    10,
                    1,
                    64,
                ],
                [
                    2,
                    77,
                    10,
                    1,
                    64,
                ],
            ],
            [
                [
                    2,
                    4096,
                    10,
                    1,
                    64,
                ],
                [
                    2,
                    4096,
                    10,
                    1,
                    64,
                ],
                [
                    2,
                    4096,
                    10,
                    1,
                    64,
                ],
                [
                    2,
                    4096,
                    10,
                    1,
                    64,
                ],
            ],
        ],
    },
    'cross_attn': {
        'format': 'triton',
        'entry': 'flash_attn_bshd_wide_k',
        'file': 'cross_attn.triton.py',
        'sha256': '317c2694ec416871a767cafb2d639d64bc9bbc023340c3592757c86c0dedad11',
        'num_warps': 4,
        'num_stages': 2,
        'constexpr_variants': [
            {
                'BLOCK_M': 128,
                'BLOCK_N': 128,
                'HEAD_DIM': 64,
                'KV_LEN': 77,
                'KV_ROW_STRIDE': 2560,
                'K_COL': 0,
                'NUM_HEADS': 10,
                'Q_LEN': 4096,
                'V_COL': 640,
            },
            {
                'BLOCK_M': 128,
                'BLOCK_N': 128,
                'HEAD_DIM': 64,
                'KV_LEN': 77,
                'KV_ROW_STRIDE': 2560,
                'K_COL': 1280,
                'NUM_HEADS': 10,
                'Q_LEN': 4096,
                'V_COL': 1920,
            },
            {
                'BLOCK_M': 128,
                'BLOCK_N': 128,
                'HEAD_DIM': 64,
                'KV_LEN': 77,
                'KV_ROW_STRIDE': 25600,
                'K_COL': 0,
                'NUM_HEADS': 20,
                'Q_LEN': 1024,
                'V_COL': 1280,
            },
            {
                'BLOCK_M': 128,
                'BLOCK_N': 128,
                'HEAD_DIM': 64,
                'KV_LEN': 77,
                'KV_ROW_STRIDE': 25600,
                'K_COL': 2560,
                'NUM_HEADS': 20,
                'Q_LEN': 1024,
                'V_COL': 3840,
            },
            {
                'BLOCK_M': 128,
                'BLOCK_N': 128,
                'HEAD_DIM': 64,
                'KV_LEN': 77,
                'KV_ROW_STRIDE': 25600,
                'K_COL': 5120,
                'NUM_HEADS': 20,
                'Q_LEN': 1024,
                'V_COL': 6400,
            },
            {
                'BLOCK_M': 128,
                'BLOCK_N': 128,
                'HEAD_DIM': 64,
                'KV_LEN': 77,
                'KV_ROW_STRIDE': 25600,
                'K_COL': 7680,
                'NUM_HEADS': 20,
                'Q_LEN': 1024,
                'V_COL': 8960,
            },
            {
                'BLOCK_M': 128,
                'BLOCK_N': 128,
                'HEAD_DIM': 64,
                'KV_LEN': 77,
                'KV_ROW_STRIDE': 25600,
                'K_COL': 10240,
                'NUM_HEADS': 20,
                'Q_LEN': 1024,
                'V_COL': 11520,
            },
            {
                'BLOCK_M': 128,
                'BLOCK_N': 128,
                'HEAD_DIM': 64,
                'KV_LEN': 77,
                'KV_ROW_STRIDE': 25600,
                'K_COL': 12800,
                'NUM_HEADS': 20,
                'Q_LEN': 1024,
                'V_COL': 14080,
            },
            {
                'BLOCK_M': 128,
                'BLOCK_N': 128,
                'HEAD_DIM': 64,
                'KV_LEN': 77,
                'KV_ROW_STRIDE': 25600,
                'K_COL': 15360,
                'NUM_HEADS': 20,
                'Q_LEN': 1024,
                'V_COL': 16640,
            },
            {
                'BLOCK_M': 128,
                'BLOCK_N': 128,
                'HEAD_DIM': 64,
                'KV_LEN': 77,
                'KV_ROW_STRIDE': 25600,
                'K_COL': 17920,
                'NUM_HEADS': 20,
                'Q_LEN': 1024,
                'V_COL': 19200,
            },
            {
                'BLOCK_M': 128,
                'BLOCK_N': 128,
                'HEAD_DIM': 64,
                'KV_LEN': 77,
                'KV_ROW_STRIDE': 25600,
                'K_COL': 20480,
                'NUM_HEADS': 20,
                'Q_LEN': 1024,
                'V_COL': 21760,
            },
            {
                'BLOCK_M': 128,
                'BLOCK_N': 128,
                'HEAD_DIM': 64,
                'KV_LEN': 77,
                'KV_ROW_STRIDE': 25600,
                'K_COL': 23040,
                'NUM_HEADS': 20,
                'Q_LEN': 1024,
                'V_COL': 24320,
            },
        ],
    },
    'bias_residual_ln_w640': {
        'format': 'cuda',
        'entry': 'bias_residual_ln_w640_k',
        'file': 'bias_residual_ln_w640.cu',
        'sha256': '9dd6fa4833a4add9d39394e5a47828e50a62d7ccde12e8137075cacf893b6621',
        'grid': [
            8192,
            1,
            1,
        ],
        'block': [
            128,
            1,
            1,
        ],
    },
    'bias_residual_ln_w1280': {
        'format': 'cuda',
        'entry': 'bias_residual_ln_w1280_k',
        'file': 'bias_residual_ln_w1280.cu',
        'sha256': 'f280c99ee5aa8cff9775e19a54acd7769c89027ee00cdaa74c8160832effb667',
        'grid': [
            2048,
            1,
            1,
        ],
        'block': [
            128,
            1,
            1,
        ],
    },
    'fmha_d512': {
        'format': 'cutedsl',
        'entry': 'fmha_d512_bf16_np_entry',
        'file': 'fmha_d512.cutedsl.py',
        'sha256': '3a5823d03e05800adb8ea0a10e25c15684ddd70d74931d22940afbb4fe23207d',
        'options': '--opt-level=2',
        'compile_variants': [
            {},
        ],
        'shape_variants': [
            [
                [
                    1,
                    16384,
                    1,
                    1,
                    512,
                ],
                [
                    1,
                    16384,
                    1,
                    1,
                    512,
                ],
                [
                    1,
                    16384,
                    1,
                    1,
                    512,
                ],
                [
                    1,
                    16384,
                    1,
                    1,
                    512,
                ],
            ],
        ],
    },
}
